- ourJourney/src/main/java/pudding/toy/ourJourney/common/HttpStatusCode.java
- ourJourney/src/main/java/pudding/toy/ourJourney/common/response/BaseResponse.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/AuthController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/ProfileAuthResponseDto.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/ProfileEditRequestDto.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/ProfileResponseDto.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Post.java
- ourJourney/src/main/java/pudding/toy/ourJourney/repository/ProfileRepository.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ProfileService.java
💾 BackUp: profile 관련 기능 백업 + profile dto 변수명 고치기
- 포크따서 작업하던 브랜치를 옮긴 후 날라갔던 파일을 다시 재업합니닷
- 피드백 받고`ProfileRequestDto`를 `ProfileAuthResponseDto`로 변경합니다.
- 이슈를 안 올렸는데 백업 후 다시 작업할 때는 이슈를 올리겠습니다
- 없습니다! 백업하고 나서 다시 깃헙 푸쉬 하겠습니다. 
- Post 관련한 CRUD를 우선적으로 구현할 예정입니다.
- 없습니다.
> 💾 Backup: profile 관련 기능 백업 + profile dto 변수명 고치기

- .gitignore
- ourJourney/build.gradle
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/PostContentResponseDto.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Attendee.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Category.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Comment.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Contents.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/ContentsThread.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/PostLike.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/PostTag.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Profile.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/ThreadTag.java
- ourJourney/src/main/java/pudding/toy/ourJourney/repository/PostRepository.java
- ourJourney/src/main/java/pudding/toy/ourJourney/repository/TagRepository.java
- ourJourney/src/main/java/pudding/toy/ourJourney/repository/ThreadRepository.java
- ourJourney/src/main/java/resources/application.yml
실행이 안되는 문제 해결
- application.yml gitignore에서 제거
- 로컬 개발용으로 h2 데이터베이스 추가
- spring security 임시로 제거
- Thread 이름 겹치는 문제 수정, Contents entity 이름 변경
> fix: 실행이 안되는 문제 해결

- .gitignore
- ourJourney/build.gradle
- ourJourney/src/main/java/pudding/toy/ourJourney/config/SwaggerConfig.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/HealthController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/PostContentResponseDto.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Attendee.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Category.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Comment.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Contents.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/ContentsThread.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/PostLike.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/PostTag.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Profile.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/ThreadTag.java
- ourJourney/src/main/java/pudding/toy/ourJourney/repository/PostRepository.java
- ourJourney/src/main/java/pudding/toy/ourJourney/repository/TagRepository.java
- ourJourney/src/main/java/pudding/toy/ourJourney/repository/ThreadRepository.java
- ourJourney/src/main/java/resources/application.yml
swagger 기본 설정
- swagger 사용을 위해 springdoc-openapi 추가
- health check 용 api 추가
https://github.com/Spoon-Lab/OurJourney-BE/pull/17
위 PR이 먼저 merge되어야합니다
https://springdoc.org/
https://colabear754.tistory.com/99
> feat: swagger 기본 설정

- ourJourney/src/main/java/pudding/toy/ourJourney/controller/CommentController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/comment/CommentProfileDto.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/comment/CreateCommentRequest.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/comment/CreateCommentResponse.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/comment/CreateReCommentRequest.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/comment/CreateReCommentResponse.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/comment/GetCommentResponse.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/comment/GetCommentsDto.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/comment/UpdateCommentRequest.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Comment.java
댓글 api 문서화하였습니다
아래와 같은 api를 문서화하였습니다
- 댓글 생성
- 대댓글 생성
- 댓글 목록
- 댓글 수정
- 댓글 삭제
해시태그 api와 프로필 api들 문서화 예정입니다
> docs: 댓글 api 문서화

- ourJourney/src/main/java/pudding/toy/ourJourney/controller/TagsController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/tags/CreateTagsRequest.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/tags/GetTagsDto.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/tags/GetTagsResponse.java
해시태그api 문서화
- 해시태그 생성 api
- 해시태그 목록 api
- PageImpl을 바로 return 했었으나 Response 객체로 한번 감싸서 내리는게 추가적은 필드 만들기에 좋아서 변경했습니다
> docs: 해시태그api 문서화

- ourJourney/src/main/java/pudding/toy/ourJourney/controller/TagsController.java
tags api에 tag 추가
tags api에 tag가 없으니 swagger에서 tags-controller라고 나와서 추가했습니다
> docs: tags api에 tag 추가

- ourJourney/src/main/java/pudding/toy/ourJourney/controller/CategoryController.java
category api에 달린 tag 이름이 달라서 수정
> docs: category api에 달린 tag 이름이 달라서 수정

- ourJourney/src/main/java/pudding/toy/ourJourney/controller/CategoryController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/category/CategoryDto.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/category/GetCategoriesResponse.java
category API 문서화
category API 문서화 했습니다.
> :memo: docs: category API 문서화

- ourJourney/build.gradle
- ourJourney/src/main/java/pudding/toy/ourJourney/config/QueryDSLConfig.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/ContentController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Category.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Contents.java
- ourJourney/src/main/java/pudding/toy/ourJourney/repository/ContentsQueryRepository.java
- ourJourney/src/test/java/pudding/toy/ourJourney/repository/ContentsQueryRepositoryTest.java
querydsl 설정 및 글 검색 query repository 추가
- querydsl 설정을 추가하였습니다  
- 예시용으로 글 검색하는 query repository도 추가하였습니다
- 사용법은 테스트코드로 작성해놨습니다
https://velog.io/@kimsundae/Gradle-SpringBoot-3.x-QueryDSL-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0
https://c-king.tistory.com/546
> feat: querydsl 설정 및 글 검색 query repository 추가

- ourJourney/src/main/java/pudding/toy/ourJourney/controller/CommentController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Comment.java
- ourJourney/src/main/java/pudding/toy/ourJourney/repository/CommentRepository.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/CommentService.java
- ourJourney/src/test/java/pudding/toy/ourJourney/mapper/JacksonConfigTest.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/AttendeeServiceTest.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/CommentServiceTest.java
댓글 리스트 api
- 안돌아가는 테스트 코드가 있어서 수정했습니다
- 댓글 리스트를 내려주는 api를 작성했습니다
> feat: 댓글 리스트 api

- ourJourney/src/main/java/pudding/toy/ourJourney/controller/CommentController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/BaseTimeEntity.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Comment.java
- ourJourney/src/main/java/pudding/toy/ourJourney/repository/CommentRepository.java
- ourJourney/src/main/java/pudding/toy/ourJourney/repository/ContentRepository.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/CommentService.java
- ourJourney/src/main/resources/application.yml
- ourJourney/src/test/java/pudding/toy/ourJourney/mapper/JacksonConfigTest.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/AttendeeServiceTest.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/CommentServiceTest.java
댓글 삭제 api
- 댓글 삭제 api를 작성하였습니다
- 소프트 딜리트가 제대로 동작 안하는거 같아서 일단 deletedAt이 null인것을 가져오도록 쿼리를 수정해서 쓰는중입니다
> feat: 댓글 삭제 api

- ourJourney/build.gradle
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/ProfileController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/auth/ProfileAuthResponseDto.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/profile/NewProfileResponse.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Profile.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ContentService.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ProfileService.java
- ourJourney/src/test/java/pudding/toy/ourJourney/repository/ContentsQueryRepositoryTest.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/AttendeeServiceTest.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/CommentServiceTest.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/NickNameRandomServiceTest.java
:sparkles: CreateProfile 로직 구현 + 디폴트 닉네임 설정
- createProfile 로직을 구현했습니다.
- 이 과정에서 디폴트 닉네임을 지정해주느라, profile에서 불필요한 생성자를 지웠고, 이러면서 테스트 코드에서 Profile을 생성하는 코드들의 에러가 나서 제가 지웠습니다.. (죄송합니닷)
- profile을 생성할 때 장고로 부터 유저 이메일을 받는데 그럴 필요가 없을 것 같아 일단 ProfileAuthResponse(장고가 주는 response) 를 받는걸로 바꿨습니다.
- createRandomNickName() 생성. (귀여운푸딩(랜덤숫자))이런식으로 뜹니다!
[랜덤 함수에 대해서](https://coding-factory.tistory.com/530)
- `ProfileAuthResponse` : 장고가 프로필 생성을 위해 회원가입 후 스프링에게 요청하는 DTO입니다. 저번에 루나님이 Response가 어떻냐고 제안 주셔서 바꿨는데, 이번엔 저희가 프로필 생성 요청을 받는 쪽이라고 생각해서 Request로 바꿔도 될 것 같기도 한데 어떻게 생각하세요?
- 형용사 리스트를 메소드가 실행될 때마다 초기화 시키기 싫어서 final로 초기화시켰는데 너무 미운 코드인지(??) 괜찮나요? 
- 나머지 로직과 좋아요나 팔로우를 구현하기.
> :sparkles: CreateProfile 로직 구현 + 디폴트 닉네임 설정

- ourJourney/src/main/java/pudding/toy/ourJourney/controller/ThreadController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/thread/CreateThreadResponse.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/ContentsThread.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/ThreadTag.java
- ourJourney/src/main/java/pudding/toy/ourJourney/repository/ThreadRepository.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ThreadService.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/ThreadServiceTest.java
> feat: 스레드 리스트, 생성 api

- ourJourney/src/main/java/pudding/toy/ourJourney/controller/TagsController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/repository/TagRepository.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/TagService.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/TagServiceTest.java
> feat: 태그 리스트 api 추가

- ourJourney/.gitignore
> chore: 자동 생성되는 파일 ignore 추가

- ourJourney/src/main/java/pudding/toy/ourJourney/config/DummyDataInitializer.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/CommentController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/ContentController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/FollowController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/TagsController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/ThreadController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/content/ListContentDto.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ContentService.java
- ourJourney/src/main/resources/application.yml
- ourJourney/src/test/java/pudding/toy/ourJourney/mapper/ContentMapperTest.java
- ourJourney/src/test/java/pudding/toy/ourJourney/repository/ContentsQueryRepositoryTest.java
- ourJourney/src/test/java/pudding/toy/ourJourney/repository/ThreadsQueryRepositoryTest.java
더미 데이터 추가
- 뭔가 전체적으로 버그가 좀 있는거 같네요 제가 만든것도 포함입니다.
> chore: 더미 데이터 추가

- ourJourney/src/main/java/pudding/toy/ourJourney/config/WebConfig.java
> feat: cors 설정 추가

- ourJourney/src/main/java/pudding/toy/ourJourney/dto/auth/ProfileAuthRequest.java
> :bug: JsonProperty 제거

- ourJourney/src/main/java/pudding/toy/ourJourney/entity/BaseTimeEntity.java
:recycle: refactor: created_at 으로 칼럼 이름 수정
if문은.... 방안이 없어보이네요 🤔
> :recycle: refactor: created_at 으로 칼럼 이름 수정

- ourJourney/.gitignore
- ourJourney/build.gradle
- ourJourney/src/main/java/pudding/toy/ourJourney/config/DummyDataInitializer.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/BaseTimeEntity.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Profile.java
- ourJourney/src/main/resources/application.yml
- ourJourney/src/test/java/pudding/toy/ourJourney/mapper/ContentMapperTest.java
- ourJourney/src/test/java/pudding/toy/ourJourney/repository/ContentsQueryRepositoryTest.java
- ourJourney/src/test/java/pudding/toy/ourJourney/repository/ThreadsQueryRepositoryTest.java
> feat: env 사용해서 production phase 적용

- ourJourney/src/main/resources/application.yml
default profiles를 development로 설정
> chore: default profiles를 development로 설정

- ourJourney/src/main/java/pudding/toy/ourJourney/controller/CategoryController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/FollowController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/category/CategoryDto.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/category/GetCategoriesResponse.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/content/DetailContentResponse.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/content/ListContentDto.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/BaseTimeEntity.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Category.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/CategoryService.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ProfileService.java
카테고리 목록 api
- 카테고리 목록 api
- 카테고리에 반영 안된 필드들이 있어서 수정했습니다
> feat: 카테고리 목록 api

- ourJourney/src/main/java/pudding/toy/ourJourney/config/SecurityConfig.java
> fix: security 버그 수정

- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Follow.java
> fix: follow 매핑 다른거 수정

- ourJourney/src/main/java/pudding/toy/ourJourney/entity/ContentLike.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/ContentsThread.java
post_id로 되어 있던거 content_id로 수정
> fix: post_id로 되어 있던거 content_id로 수정

- our_journey_admin/apps/userapp/apps.py
- our_journey_admin/config/asgi.py
- our_journey_admin/config/urls.py
- our_journey_admin/config/wsgi.py
- our_journey_admin/manage.py
gitignore 파일 추가
django 관련 ignore 작성한 것이 사라져있어서 다시 추가했습니다.
> chore: gitignore 파일 추가

- our_journey_admin/.env
django env 파일 삭제
gitignore가 반영이 안 되면서 django env 파일이 레포에 올라갔던 것을 확인하고 삭제합니다.
> chore: django env파일 삭제

- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Attendee.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Comment.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/ContentTag.java
> fix: 컬럼의 content_id가 달라서 맞춤

- ourJourney/src/main/java/pudding/toy/ourJourney/entity/ContentsThread.java
> fix: thread의 texts 필드 이름 다른거 수정

- ourJourney/src/main/java/pudding/toy/ourJourney/controller/ContentController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/ThreadController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/content/DetailContentResponse.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/thread/ListThreadDto.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ContentService.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ThreadService.java
글상세, 스레드 리스트 api에 수정, 삭제 가능한지 여부를 알려주는 필드 추가
> feat: 글상세, 스레드 리스트 api에 수정, 삭제 가능한지 여부를 알려주는 필드 추가

- ourJourney/src/main/java/pudding/toy/ourJourney/controller/CategoryController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/CommentController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/ContentController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/FollowController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/ThreadController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/AuthService.java
> feat: AuthService 적용

- ourJourney/src/main/java/pudding/toy/ourJourney/filter/JwtAuthenticationFilter.java
> :recycle: refactor: 스웨거 url추가

- ourJourney/src/main/java/pudding/toy/ourJourney/service/AuthService.java
> fix: anonymousUser도 사용할 수 있게 처리

- ourJourney/src/main/java/pudding/toy/ourJourney/service/ProfileService.java
> :bug: page네이션 last = true 오류 수정

- our_journey_admin/apps/userapp/apps.py
- our_journey_admin/config/asgi.py
- our_journey_admin/config/urls.py
- our_journey_admin/config/wsgi.py
- our_journey_admin/manage.py
chore: gitignore에 admin 관련 내용 추가 및 column 길이 수정
gitignore에 admin 관련 내용 추가하고 (자꾸 관련 내용이 사라져서 추가했습니다)
s3 이미지 **presigned_url**의 길이가 200자가 넘어가서 `img_url` 컬럼의 길이를 1000으로 수정하였습니다.
> chore: gitignore에 admin 관련 내용 추가 및 column 길이 수정

- ourJourney/deploy.sh
ec2 내부에서 배포하는 스크립트 추가
- ec2 내부에서 매번 배포하려고 명령어 치는게 귀찮아서 만들었습니다
> chore: ec2 내부에서 배포하는 스크립트 추가

- ourJourney/src/test/java/pudding/toy/ourJourney/service/AttendeeServiceTest.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/AuthServiceTest.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/ContentServiceTest.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/NickNameRandomServiceTest.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/TagServiceTest.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/ThreadServiceTest.java
안돌아가는 테스트 수정 및 transactional 다 붙임
> test: 안돌아가는 테스트 수정 및 transactional 다 붙임

- ourJourney/src/main/java/pudding/toy/ourJourney/filter/JwtAuthenticationFilter.java
filter에서 create profile api 예외
> fix: filter에서 create profile api 예외

- ourJourney/src/main/java/pudding/toy/ourJourney/config/DummyDataInitializer.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/CommentController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/ThreadController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/content/CreateContentRequest.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/thread/CreateThreadRequest.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/ContentsThread.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ContentService.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ThreadService.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/ThreadServiceTest.java
:bug: thread post optional로 수정
> :bug: thread post optional로 수정

- ourJourney/src/main/java/pudding/toy/ourJourney/repository/ThreadRepository.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ThreadService.java
> fix: 스레드 soft delete 조회 반영 안된곳 수정

- ourJourney/src/main/java/pudding/toy/ourJourney/controller/ContentController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/ProfileController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/ThreadController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/content/DetailContentResponse.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/content/NewLikeResponse.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/profile/GetDetailProfileResponse.java
- ourJourney/src/main/java/pudding/toy/ourJourney/filter/JwtAuthenticationFilter.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/AuthService.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ContentService.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ProfileService.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ThreadService.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/FollowServiceTest.java
:sparkles: feat: controller에 비회원 처리 + profile isEditable 처리
> :sparkles: feat: controller에 비회원 처리 + profile isEditable 처리

- ourJourney/src/main/java/pudding/toy/ourJourney/controller/ContentController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/ProfileController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/controller/ThreadController.java
- ourJourney/src/main/java/pudding/toy/ourJourney/dto/profile/GetDetailProfileResponse.java
- ourJourney/src/main/java/pudding/toy/ourJourney/filter/JwtAuthenticationFilter.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/AuthService.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ContentService.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ProfileService.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ThreadService.java
- ourJourney/src/test/java/pudding/toy/ourJourney/service/FollowServiceTest.java
:bug: fix: isLiked 항상 false 인거 버그 수정
> :bug: fix: isLiked 항상 false 인거 버그 수정

- ourJourney/src/main/java/pudding/toy/ourJourney/config/DummyDataInitializer.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/ContentsThread.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/Tag.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ContentService.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ThreadService.java
> :bug: fix: 비회원이나 get 만료시 조회 오류 수정 및 thread tag 수정

- ourJourney/src/main/java/pudding/toy/ourJourney/dto/content/UpdateContentRequest.java
- ourJourney/src/main/java/pudding/toy/ourJourney/entity/ContentLike.java
- ourJourney/src/main/java/pudding/toy/ourJourney/filter/JwtAuthenticationFilter.java
- ourJourney/src/main/java/pudding/toy/ourJourney/repository/ContentLikeRepository.java
- ourJourney/src/main/java/pudding/toy/ourJourney/repository/ContentRepository.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ContentService.java
- ourJourney/src/main/java/pudding/toy/ourJourney/service/ProfileService.java
:bug: fix: 좋아요 글 페이지네이션 수정 및 contentLike에 soft delete 적용 
- 좋아요한 글 보기 페이지네이션 작동 버그 수정
- contentLike도 soft delete 적용
> :bug: fix: 좋아요 글 페이지네이션 수정 및 soft delete 적용
